# Generated by Django 4.1 on 2022-08-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='List2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=35)),
                ('list1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shtors.list1')),
            ],
        ),
    ]
