# Generated by Django 4.1 on 2022-08-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list2',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shtors/'),
        ),
        migrations.AlterField(
            model_name='list2',
            name='name2',
            field=models.CharField(max_length=40),
        ),
    ]
