# Generated by Django 4.1 on 2022-08-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtors', '0002_list2_img_alter_list2_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='list1',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shtors/media/shtors/'),
        ),
        migrations.AlterField(
            model_name='list2',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shtors/media/shtors/'),
        ),
    ]
