# Generated by Django 4.1 on 2022-08-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtors', '0003_list1_img_alter_list2_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list1',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shtors/'),
        ),
        migrations.AlterField(
            model_name='list2',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='shtors/'),
        ),
    ]
