# Generated by Django 4.1 on 2022-08-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtors', '0005_list3'),
    ]

    operations = [
        migrations.AddField(
            model_name='list3',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='shtors/'),
        ),
        migrations.AddField(
            model_name='list3',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='shtors/'),
        ),
    ]
