# Generated by Django 4.1 on 2022-08-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shtors', '0006_list3_img1_list3_img2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list3',
            old_name='img',
            new_name='img3',
        ),
    ]
