# Generated by Django 4.1 on 2022-09-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shtors', '0009_user_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('question', models.TextField(max_length=300)),
            ],
        ),
    ]
